#ifndef NANDINA_FONTS_EXPORT_HPP
#define NANDINA_FONTS_EXPORT_HPP

#include <QtGlobal>

#if defined(NandinaFonts_EXPORTS)
#define NANDINA_FONTS_EXPORT Q_DECL_EXPORT
#else
#define NANDINA_FONTS_EXPORT Q_DECL_IMPORT
#endif

#endif // NANDINA_FONTS_EXPORT_HPP

