playground_exe = executable(
    'nandina_showcase',
    files(
        'application.cpp',
        'main_window.hpp',
        'main_window.cpp',
        'pages/home_page.hpp',
        'pages/home_page.cpp',
        'pages/avatar_page.hpp',
        'pages/avatar_page.cpp',
    ),
    dependencies : nandina_dep,
    install : false,
)
