#ifndef NANDINA_PRIMITIVES_EXPORT_HPP
#define NANDINA_PRIMITIVES_EXPORT_HPP

#include <QtGlobal>

#if defined(NandinaPrimitives_EXPORTS)
#define NANDINA_PRIMITIVES_EXPORT Q_DECL_EXPORT
#else
#define NANDINA_PRIMITIVES_EXPORT Q_DECL_IMPORT
#endif

#endif // NANDINA_PRIMITIVES_EXPORT_HPP

