//
// Auto-generated by scripts/generate_presets.py
// Do not edit manually.
//

#include "theme_presets.hpp"

using namespace Nandina::Core::Color;
using namespace Nandina::Core::Primitives;
using namespace Nandina::Types;

namespace Nandina::Core::Tokens {

bool applyPreset(ThemePreset preset, ColorSchema *colors, PrimitiveSchema *primitives) {
    switch (preset) {
        case ThemePreset::Catppuccin:
            applyCatppuccin(colors, primitives);
            return true;
        case ThemePreset::Cerberus:
            applyCerberus(colors, primitives);
            return true;
        case ThemePreset::Concord:
            applyConcord(colors, primitives);
            return true;
        case ThemePreset::Crimson:
            applyCrimson(colors, primitives);
            return true;
        case ThemePreset::Fennec:
            applyFennec(colors, primitives);
            return true;
        case ThemePreset::Legacy:
            applyLegacy(colors, primitives);
            return true;
    }
    return false;
}

void applyCatppuccin(ColorSchema *colors, PrimitiveSchema *primitives) {
    // primary
    {
        auto *p = colors->palette(ColorVariant::Primary);
        p->setColor(ColorAccent::Shade50, QColor("#e9fbff"));
        p->setColor(ColorAccent::Shade100, QColor("#d3e4fe"));
        p->setColor(ColorAccent::Shade200, QColor("#bbcdfd"));
        p->setColor(ColorAccent::Shade300, QColor("#a1b5ff"));
        p->setColor(ColorAccent::Shade400, QColor("#8a9efd"));
        p->setColor(ColorAccent::Shade500, QColor("#7186ff"));
        p->setColor(ColorAccent::Shade600, QColor("#6f81ec"));
        p->setColor(ColorAccent::Shade700, QColor("#6a7bde"));
        p->setColor(ColorAccent::Shade800, QColor("#6476d1"));
        p->setColor(ColorAccent::Shade900, QColor("#6270be"));
        p->setColor(ColorAccent::Shade950, QColor("#5d6ab0"));
        p->setColor(ColorAccent::ContrastDark, QColor("#5d6ab0"));
        p->setColor(ColorAccent::ContrastLight, QColor("#e9fbff"));
        p->setColor(ColorAccent::Contrast50, QColor("#5d6ab0"));
        p->setColor(ColorAccent::Contrast100, QColor("#5d6ab0"));
        p->setColor(ColorAccent::Contrast200, QColor("#5d6ab0"));
        p->setColor(ColorAccent::Contrast300, QColor("#5d6ab0"));
        p->setColor(ColorAccent::Contrast400, QColor("#e9fbff"));
        p->setColor(ColorAccent::Contrast500, QColor("#e9fbff"));
        p->setColor(ColorAccent::Contrast600, QColor("#e9fbff"));
        p->setColor(ColorAccent::Contrast700, QColor("#e9fbff"));
        p->setColor(ColorAccent::Contrast800, QColor("#e9fbff"));
        p->setColor(ColorAccent::Contrast900, QColor("#e9fbff"));
        p->setColor(ColorAccent::Contrast950, QColor("#e9fbff"));
    }
    // secondary
    {
        auto *p = colors->palette(ColorVariant::Secondary);
        p->setColor(ColorAccent::Shade50, QColor("#f7c1e8"));
        p->setColor(ColorAccent::Shade100, QColor("#f1b4e0"));
        p->setColor(ColorAccent::Shade200, QColor("#f3a3dd"));
        p->setColor(ColorAccent::Shade300, QColor("#f093d7"));
        p->setColor(ColorAccent::Shade400, QColor("#ee83d2"));
        p->setColor(ColorAccent::Shade500, QColor("#e977ca"));
        p->setColor(ColorAccent::Shade600, QColor("#d067b3"));
        p->setColor(ColorAccent::Shade700, QColor("#b25a9b"));
        p->setColor(ColorAccent::Shade800, QColor("#994a85"));
        p->setColor(ColorAccent::Shade900, QColor("#7c3c6d"));
        p->setColor(ColorAccent::Shade950, QColor("#612e55"));
        p->setColor(ColorAccent::ContrastDark, QColor("#612e55"));
        p->setColor(ColorAccent::ContrastLight, QColor("#f7c1e8"));
        p->setColor(ColorAccent::Contrast50, QColor("#612e55"));
        p->setColor(ColorAccent::Contrast100, QColor("#612e55"));
        p->setColor(ColorAccent::Contrast200, QColor("#612e55"));
        p->setColor(ColorAccent::Contrast300, QColor("#612e55"));
        p->setColor(ColorAccent::Contrast400, QColor("#612e55"));
        p->setColor(ColorAccent::Contrast500, QColor("#612e55"));
        p->setColor(ColorAccent::Contrast600, QColor("#612e55"));
        p->setColor(ColorAccent::Contrast700, QColor("#f7c1e8"));
        p->setColor(ColorAccent::Contrast800, QColor("#f7c1e8"));
        p->setColor(ColorAccent::Contrast900, QColor("#f7c1e8"));
        p->setColor(ColorAccent::Contrast950, QColor("#f7c1e8"));
    }
    // tertiary
    {
        auto *p = colors->palette(ColorVariant::Tertiary);
        p->setColor(ColorAccent::Shade50, QColor("#93e2d5"));
        p->setColor(ColorAccent::Shade100, QColor("#76d3c9"));
        p->setColor(ColorAccent::Shade200, QColor("#64c2bd"));
        p->setColor(ColorAccent::Shade300, QColor("#42b3b2"));
        p->setColor(ColorAccent::Shade400, QColor("#2ca2a5"));
        p->setColor(ColorAccent::Shade500, QColor("#0f9299"));
        p->setColor(ColorAccent::Shade600, QColor("#148287"));
        p->setColor(ColorAccent::Shade700, QColor("#167276"));
        p->setColor(ColorAccent::Shade800, QColor("#166264"));
        p->setColor(ColorAccent::Shade900, QColor("#155253"));
        p->setColor(ColorAccent::Shade950, QColor("#124241"));
        p->setColor(ColorAccent::ContrastDark, QColor("#124241"));
        p->setColor(ColorAccent::ContrastLight, QColor("#93e2d5"));
        p->setColor(ColorAccent::Contrast50, QColor("#124241"));
        p->setColor(ColorAccent::Contrast100, QColor("#124241"));
        p->setColor(ColorAccent::Contrast200, QColor("#124241"));
        p->setColor(ColorAccent::Contrast300, QColor("#124241"));
        p->setColor(ColorAccent::Contrast400, QColor("#124241"));
        p->setColor(ColorAccent::Contrast500, QColor("#93e2d5"));
        p->setColor(ColorAccent::Contrast600, QColor("#93e2d5"));
        p->setColor(ColorAccent::Contrast700, QColor("#93e2d5"));
        p->setColor(ColorAccent::Contrast800, QColor("#93e2d5"));
        p->setColor(ColorAccent::Contrast900, QColor("#93e2d5"));
        p->setColor(ColorAccent::Contrast950, QColor("#93e2d5"));
    }
    // success
    {
        auto *p = colors->palette(ColorVariant::Success);
        p->setColor(ColorAccent::Shade50, QColor("#a6e3a1"));
        p->setColor(ColorAccent::Shade100, QColor("#90d787"));
        p->setColor(ColorAccent::Shade200, QColor("#7dc872"));
        p->setColor(ColorAccent::Shade300, QColor("#67bc57"));
        p->setColor(ColorAccent::Shade400, QColor("#52ad41"));
        p->setColor(ColorAccent::Shade500, QColor("#3ea028"));
        p->setColor(ColorAccent::Shade600, QColor("#39902b"));
        p->setColor(ColorAccent::Shade700, QColor("#337f2c"));
        p->setColor(ColorAccent::Shade800, QColor("#2d6f2c"));
        p->setColor(ColorAccent::Shade900, QColor("#265e2b"));
        p->setColor(ColorAccent::Shade950, QColor("#1e4e2a"));
        p->setColor(ColorAccent::ContrastDark, QColor("#1e4e2a"));
        p->setColor(ColorAccent::ContrastLight, QColor("#a6e3a1"));
        p->setColor(ColorAccent::Contrast50, QColor("#1e4e2a"));
        p->setColor(ColorAccent::Contrast100, QColor("#1e4e2a"));
        p->setColor(ColorAccent::Contrast200, QColor("#1e4e2a"));
        p->setColor(ColorAccent::Contrast300, QColor("#1e4e2a"));
        p->setColor(ColorAccent::Contrast400, QColor("#1e4e2a"));
        p->setColor(ColorAccent::Contrast500, QColor("#a6e3a1"));
        p->setColor(ColorAccent::Contrast600, QColor("#a6e3a1"));
        p->setColor(ColorAccent::Contrast700, QColor("#a6e3a1"));
        p->setColor(ColorAccent::Contrast800, QColor("#a6e3a1"));
        p->setColor(ColorAccent::Contrast900, QColor("#a6e3a1"));
        p->setColor(ColorAccent::Contrast950, QColor("#a6e3a1"));
    }
    // warning
    {
        auto *p = colors->palette(ColorVariant::Warning);
        p->setColor(ColorAccent::Shade50, QColor("#f9e2af"));
        p->setColor(ColorAccent::Shade100, QColor("#f4d191"));
        p->setColor(ColorAccent::Shade200, QColor("#f0c073"));
        p->setColor(ColorAccent::Shade300, QColor("#e7b15c"));
        p->setColor(ColorAccent::Shade400, QColor("#e49f39"));
        p->setColor(ColorAccent::Shade500, QColor("#df8e1c"));
        p->setColor(ColorAccent::Shade600, QColor("#c87f11"));
        p->setColor(ColorAccent::Shade700, QColor("#ae731d"));
        p->setColor(ColorAccent::Shade800, QColor("#976414"));
        p->setColor(ColorAccent::Shade900, QColor("#7d581a"));
        p->setColor(ColorAccent::Shade950, QColor("#644a1e"));
        p->setColor(ColorAccent::ContrastDark, QColor("#644a1e"));
        p->setColor(ColorAccent::ContrastLight, QColor("#f9e2af"));
        p->setColor(ColorAccent::Contrast50, QColor("#644a1e"));
        p->setColor(ColorAccent::Contrast100, QColor("#644a1e"));
        p->setColor(ColorAccent::Contrast200, QColor("#644a1e"));
        p->setColor(ColorAccent::Contrast300, QColor("#644a1e"));
        p->setColor(ColorAccent::Contrast400, QColor("#644a1e"));
        p->setColor(ColorAccent::Contrast500, QColor("#644a1e"));
        p->setColor(ColorAccent::Contrast600, QColor("#f9e2af"));
        p->setColor(ColorAccent::Contrast700, QColor("#f9e2af"));
        p->setColor(ColorAccent::Contrast800, QColor("#f9e2af"));
        p->setColor(ColorAccent::Contrast900, QColor("#f9e2af"));
        p->setColor(ColorAccent::Contrast950, QColor("#f9e2af"));
    }
    // error
    {
        auto *p = colors->palette(ColorVariant::Error);
        p->setColor(ColorAccent::Shade50, QColor("#f38ba8"));
        p->setColor(ColorAccent::Shade100, QColor("#eb7392"));
        p->setColor(ColorAccent::Shade200, QColor("#e7577c"));
        p->setColor(ColorAccent::Shade300, QColor("#dd4466"));
        p->setColor(ColorAccent::Shade400, QColor("#d9274f"));
        p->setColor(ColorAccent::Shade500, QColor("#d40338"));
        p->setColor(ColorAccent::Shade600, QColor("#bd0a36"));
        p->setColor(ColorAccent::Shade700, QColor("#a80f34"));
        p->setColor(ColorAccent::Shade800, QColor("#921132"));
        p->setColor(ColorAccent::Shade900, QColor("#7d122f"));
        p->setColor(ColorAccent::Shade950, QColor("#65172d"));
        p->setColor(ColorAccent::ContrastDark, QColor("#65172d"));
        p->setColor(ColorAccent::ContrastLight, QColor("#f38ba8"));
        p->setColor(ColorAccent::Contrast50, QColor("#65172d"));
        p->setColor(ColorAccent::Contrast100, QColor("#65172d"));
        p->setColor(ColorAccent::Contrast200, QColor("#65172d"));
        p->setColor(ColorAccent::Contrast300, QColor("#65172d"));
        p->setColor(ColorAccent::Contrast400, QColor("#65172d"));
        p->setColor(ColorAccent::Contrast500, QColor("#f38ba8"));
        p->setColor(ColorAccent::Contrast600, QColor("#f38ba8"));
        p->setColor(ColorAccent::Contrast700, QColor("#f38ba8"));
        p->setColor(ColorAccent::Contrast800, QColor("#f38ba8"));
        p->setColor(ColorAccent::Contrast900, QColor("#f38ba8"));
        p->setColor(ColorAccent::Contrast950, QColor("#f38ba8"));
    }
    // surface
    {
        auto *p = colors->palette(ColorVariant::Surface);
        p->setColor(ColorAccent::Shade50, QColor("#dde0e7"));
        p->setColor(ColorAccent::Shade100, QColor("#cdd0d7"));
        p->setColor(ColorAccent::Shade200, QColor("#bbc0ce"));
        p->setColor(ColorAccent::Shade300, QColor("#acafbd"));
        p->setColor(ColorAccent::Shade400, QColor("#9d9fad"));
        p->setColor(ColorAccent::Shade500, QColor("#8c8fa3"));
        p->setColor(ColorAccent::Shade600, QColor("#76788b"));
        p->setColor(ColorAccent::Shade700, QColor("#606275"));
        p->setColor(ColorAccent::Shade800, QColor("#4a4b5d"));
        p->setColor(ColorAccent::Shade900, QColor("#343546"));
        p->setColor(ColorAccent::Shade950, QColor("#1e1e2e"));
        p->setColor(ColorAccent::ContrastDark, QColor("#1e1e2e"));
        p->setColor(ColorAccent::ContrastLight, QColor("#dde0e7"));
        p->setColor(ColorAccent::Contrast50, QColor("#1e1e2e"));
        p->setColor(ColorAccent::Contrast100, QColor("#1e1e2e"));
        p->setColor(ColorAccent::Contrast200, QColor("#1e1e2e"));
        p->setColor(ColorAccent::Contrast300, QColor("#1e1e2e"));
        p->setColor(ColorAccent::Contrast400, QColor("#1e1e2e"));
        p->setColor(ColorAccent::Contrast500, QColor("#1e1e2e"));
        p->setColor(ColorAccent::Contrast600, QColor("#1e1e2e"));
        p->setColor(ColorAccent::Contrast700, QColor("#dde0e7"));
        p->setColor(ColorAccent::Contrast800, QColor("#dde0e7"));
        p->setColor(ColorAccent::Contrast900, QColor("#dde0e7"));
        p->setColor(ColorAccent::Contrast950, QColor("#dde0e7"));
    }

    // Primitives
    primitives->setSpacing(4.0);
    primitives->setTextScaling(1.067);
    primitives->setRadiusBase(6.0);
    primitives->setRadiusContainer(12.0);
    primitives->setBorderWidth(1.0);
    primitives->setDivideWidth(1.0);
    primitives->setRingWidth(1.0);
    primitives->setBodyBackgroundColor(QColor("#ffffff"));
    primitives->setBodyBackgroundColorDark(QColor("#1e1e2e"));

    // base typography
    {
        auto *typo = primitives->baseFont();
        typo->setFontFamily(QStringLiteral("ui-rounded"));
        typo->setFontWeight(400);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#606275"));
        typo->setFontColorDark(QColor("#dde0e7"));
    }

    // heading typography
    {
        auto *typo = primitives->headingFont();
        typo->setFontFamily(QStringLiteral("Seravek"));
        typo->setFontWeight(800);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#93e2d5"));
        typo->setFontColorDark(QColor("#f3a3dd"));
    }

    // anchor typography
    {
        auto *typo = primitives->anchorFont();
        typo->setFontWeight(400);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#d067b3"));
        typo->setFontColorDark(QColor("#2ca2a5"));
    }
}

void applyCerberus(ColorSchema *colors, PrimitiveSchema *primitives) {
    // primary
    {
        auto *p = colors->palette(ColorVariant::Primary);
        p->setColor(ColorAccent::Shade50, QColor("#d4e6ff"));
        p->setColor(ColorAccent::Shade100, QColor("#a7cefe"));
        p->setColor(ColorAccent::Shade200, QColor("#83b8f9"));
        p->setColor(ColorAccent::Shade300, QColor("#57a1f9"));
        p->setColor(ColorAccent::Shade400, QColor("#2787f8"));
        p->setColor(ColorAccent::Shade500, QColor("#0770ef"));
        p->setColor(ColorAccent::Shade600, QColor("#0662d3"));
        p->setColor(ColorAccent::Shade700, QColor("#0052b4"));
        p->setColor(ColorAccent::Shade800, QColor("#064491"));
        p->setColor(ColorAccent::Shade900, QColor("#09366f"));
        p->setColor(ColorAccent::Shade950, QColor("#0b284f"));
        p->setColor(ColorAccent::ContrastDark, QColor("#0b284f"));
        p->setColor(ColorAccent::ContrastLight, QColor("#d4e6ff"));
        p->setColor(ColorAccent::Contrast50, QColor("#0b284f"));
        p->setColor(ColorAccent::Contrast100, QColor("#0b284f"));
        p->setColor(ColorAccent::Contrast200, QColor("#0b284f"));
        p->setColor(ColorAccent::Contrast300, QColor("#0b284f"));
        p->setColor(ColorAccent::Contrast400, QColor("#0b284f"));
        p->setColor(ColorAccent::Contrast500, QColor("#d4e6ff"));
        p->setColor(ColorAccent::Contrast600, QColor("#d4e6ff"));
        p->setColor(ColorAccent::Contrast700, QColor("#d4e6ff"));
        p->setColor(ColorAccent::Contrast800, QColor("#d4e6ff"));
        p->setColor(ColorAccent::Contrast900, QColor("#d4e6ff"));
        p->setColor(ColorAccent::Contrast950, QColor("#d4e6ff"));
    }
    // secondary
    {
        auto *p = colors->palette(ColorVariant::Secondary);
        p->setColor(ColorAccent::Shade50, QColor("#d9cdf1"));
        p->setColor(ColorAccent::Shade100, QColor("#c6adea"));
        p->setColor(ColorAccent::Shade200, QColor("#b189df"));
        p->setColor(ColorAccent::Shade300, QColor("#a06adb"));
        p->setColor(ColorAccent::Shade400, QColor("#8a48cf"));
        p->setColor(ColorAccent::Shade500, QColor("#7926cb"));
        p->setColor(ColorAccent::Shade600, QColor("#6a22b5"));
        p->setColor(ColorAccent::Shade700, QColor("#5e23a4"));
        p->setColor(ColorAccent::Shade800, QColor("#4e1f90"));
        p->setColor(ColorAccent::Shade900, QColor("#401c7c"));
        p->setColor(ColorAccent::Shade950, QColor("#321868"));
        p->setColor(ColorAccent::ContrastDark, QColor("#321868"));
        p->setColor(ColorAccent::ContrastLight, QColor("#d9cdf1"));
        p->setColor(ColorAccent::Contrast50, QColor("#321868"));
        p->setColor(ColorAccent::Contrast100, QColor("#321868"));
        p->setColor(ColorAccent::Contrast200, QColor("#321868"));
        p->setColor(ColorAccent::Contrast300, QColor("#321868"));
        p->setColor(ColorAccent::Contrast400, QColor("#d9cdf1"));
        p->setColor(ColorAccent::Contrast500, QColor("#d9cdf1"));
        p->setColor(ColorAccent::Contrast600, QColor("#d9cdf1"));
        p->setColor(ColorAccent::Contrast700, QColor("#d9cdf1"));
        p->setColor(ColorAccent::Contrast800, QColor("#d9cdf1"));
        p->setColor(ColorAccent::Contrast900, QColor("#d9cdf1"));
        p->setColor(ColorAccent::Contrast950, QColor("#d9cdf1"));
    }
    // tertiary
    {
        auto *p = colors->palette(ColorVariant::Tertiary);
        p->setColor(ColorAccent::Shade50, QColor("#ffcffc"));
        p->setColor(ColorAccent::Shade100, QColor("#ffa5e2"));
        p->setColor(ColorAccent::Shade200, QColor("#ff7cca"));
        p->setColor(ColorAccent::Shade300, QColor("#ff4eb0"));
        p->setColor(ColorAccent::Shade400, QColor("#fc2a97"));
        p->setColor(ColorAccent::Shade500, QColor("#ff0881"));
        p->setColor(ColorAccent::Shade600, QColor("#e30073"));
        p->setColor(ColorAccent::Shade700, QColor("#c90068"));
        p->setColor(ColorAccent::Shade800, QColor("#ad005a"));
        p->setColor(ColorAccent::Shade900, QColor("#910950"));
        p->setColor(ColorAccent::Shade950, QColor("#760243"));
        p->setColor(ColorAccent::ContrastDark, QColor("#760243"));
        p->setColor(ColorAccent::ContrastLight, QColor("#ffcffc"));
        p->setColor(ColorAccent::Contrast50, QColor("#760243"));
        p->setColor(ColorAccent::Contrast100, QColor("#760243"));
        p->setColor(ColorAccent::Contrast200, QColor("#760243"));
        p->setColor(ColorAccent::Contrast300, QColor("#760243"));
        p->setColor(ColorAccent::Contrast400, QColor("#ffcffc"));
        p->setColor(ColorAccent::Contrast500, QColor("#ffcffc"));
        p->setColor(ColorAccent::Contrast600, QColor("#ffcffc"));
        p->setColor(ColorAccent::Contrast700, QColor("#ffcffc"));
        p->setColor(ColorAccent::Contrast800, QColor("#ffcffc"));
        p->setColor(ColorAccent::Contrast900, QColor("#ffcffc"));
        p->setColor(ColorAccent::Contrast950, QColor("#ffcffc"));
    }
    // success
    {
        auto *p = colors->palette(ColorVariant::Success);
        p->setColor(ColorAccent::Shade50, QColor("#a7ffec"));
        p->setColor(ColorAccent::Shade100, QColor("#96fbe5"));
        p->setColor(ColorAccent::Shade200, QColor("#83f3da"));
        p->setColor(ColorAccent::Shade300, QColor("#70eed3"));
        p->setColor(ColorAccent::Shade400, QColor("#5de9ca"));
        p->setColor(ColorAccent::Shade500, QColor("#56e3c2"));
        p->setColor(ColorAccent::Shade600, QColor("#3cc0a4"));
        p->setColor(ColorAccent::Shade700, QColor("#319a84"));
        p->setColor(ColorAccent::Shade800, QColor("#257566"));
        p->setColor(ColorAccent::Shade900, QColor("#1b5249"));
        p->setColor(ColorAccent::Shade950, QColor("#0a2d29"));
        p->setColor(ColorAccent::ContrastDark, QColor("#0a2d29"));
        p->setColor(ColorAccent::ContrastLight, QColor("#a7ffec"));
        p->setColor(ColorAccent::Contrast50, QColor("#0a2d29"));
        p->setColor(ColorAccent::Contrast100, QColor("#0a2d29"));
        p->setColor(ColorAccent::Contrast200, QColor("#0a2d29"));
        p->setColor(ColorAccent::Contrast300, QColor("#0a2d29"));
        p->setColor(ColorAccent::Contrast400, QColor("#0a2d29"));
        p->setColor(ColorAccent::Contrast500, QColor("#0a2d29"));
        p->setColor(ColorAccent::Contrast600, QColor("#0a2d29"));
        p->setColor(ColorAccent::Contrast700, QColor("#a7ffec"));
        p->setColor(ColorAccent::Contrast800, QColor("#a7ffec"));
        p->setColor(ColorAccent::Contrast900, QColor("#a7ffec"));
        p->setColor(ColorAccent::Contrast950, QColor("#a7ffec"));
    }
    // warning
    {
        auto *p = colors->palette(ColorVariant::Warning);
        p->setColor(ColorAccent::Shade50, QColor("#fff0cc"));
        p->setColor(ColorAccent::Shade100, QColor("#fce5bb"));
        p->setColor(ColorAccent::Shade200, QColor("#fad9a2"));
        p->setColor(ColorAccent::Shade300, QColor("#fad18a"));
        p->setColor(ColorAccent::Shade400, QColor("#f9c46e"));
        p->setColor(ColorAccent::Shade500, QColor("#f7b74e"));
        p->setColor(ColorAccent::Shade600, QColor("#e3a349"));
        p->setColor(ColorAccent::Shade700, QColor("#d38d37"));
        p->setColor(ColorAccent::Shade800, QColor("#c37827"));
        p->setColor(ColorAccent::Shade900, QColor("#b26417"));
        p->setColor(ColorAccent::Shade950, QColor("#a14e0b"));
        p->setColor(ColorAccent::ContrastDark, QColor("#a14e0b"));
        p->setColor(ColorAccent::ContrastLight, QColor("#fff0cc"));
        p->setColor(ColorAccent::Contrast50, QColor("#a14e0b"));
        p->setColor(ColorAccent::Contrast100, QColor("#a14e0b"));
        p->setColor(ColorAccent::Contrast200, QColor("#a14e0b"));
        p->setColor(ColorAccent::Contrast300, QColor("#a14e0b"));
        p->setColor(ColorAccent::Contrast400, QColor("#a14e0b"));
        p->setColor(ColorAccent::Contrast500, QColor("#a14e0b"));
        p->setColor(ColorAccent::Contrast600, QColor("#fff0cc"));
        p->setColor(ColorAccent::Contrast700, QColor("#fff0cc"));
        p->setColor(ColorAccent::Contrast800, QColor("#fff0cc"));
        p->setColor(ColorAccent::Contrast900, QColor("#fff0cc"));
        p->setColor(ColorAccent::Contrast950, QColor("#fff0cc"));
    }
    // error
    {
        auto *p = colors->palette(ColorVariant::Error);
        p->setColor(ColorAccent::Shade50, QColor("#f7d4d6"));
        p->setColor(ColorAccent::Shade100, QColor("#f2b6b5"));
        p->setColor(ColorAccent::Shade200, QColor("#f29795"));
        p->setColor(ColorAccent::Shade300, QColor("#f47b74"));
        p->setColor(ColorAccent::Shade400, QColor("#f45a52"));
        p->setColor(ColorAccent::Shade500, QColor("#f53f33"));
        p->setColor(ColorAccent::Shade600, QColor("#df3229"));
        p->setColor(ColorAccent::Shade700, QColor("#cc2921"));
        p->setColor(ColorAccent::Shade800, QColor("#ba2019"));
        p->setColor(ColorAccent::Shade900, QColor("#a5100c"));
        p->setColor(ColorAccent::Shade950, QColor("#940402"));
        p->setColor(ColorAccent::ContrastDark, QColor("#940402"));
        p->setColor(ColorAccent::ContrastLight, QColor("#f7d4d6"));
        p->setColor(ColorAccent::Contrast50, QColor("#940402"));
        p->setColor(ColorAccent::Contrast100, QColor("#940402"));
        p->setColor(ColorAccent::Contrast200, QColor("#940402"));
        p->setColor(ColorAccent::Contrast300, QColor("#940402"));
        p->setColor(ColorAccent::Contrast400, QColor("#f7d4d6"));
        p->setColor(ColorAccent::Contrast500, QColor("#f7d4d6"));
        p->setColor(ColorAccent::Contrast600, QColor("#f7d4d6"));
        p->setColor(ColorAccent::Contrast700, QColor("#f7d4d6"));
        p->setColor(ColorAccent::Contrast800, QColor("#f7d4d6"));
        p->setColor(ColorAccent::Contrast900, QColor("#f7d4d6"));
        p->setColor(ColorAccent::Contrast950, QColor("#f7d4d6"));
    }
    // surface
    {
        auto *p = colors->palette(ColorVariant::Surface);
        p->setColor(ColorAccent::Shade50, QColor("#fcfcfc"));
        p->setColor(ColorAccent::Shade100, QColor("#e1e1e1"));
        p->setColor(ColorAccent::Shade200, QColor("#c1c1c1"));
        p->setColor(ColorAccent::Shade300, QColor("#a4a4a4"));
        p->setColor(ColorAccent::Shade400, QColor("#868686"));
        p->setColor(ColorAccent::Shade500, QColor("#666666"));
        p->setColor(ColorAccent::Shade600, QColor("#555555"));
        p->setColor(ColorAccent::Shade700, QColor("#454545"));
        p->setColor(ColorAccent::Shade800, QColor("#333333"));
        p->setColor(ColorAccent::Shade900, QColor("#222222"));
        p->setColor(ColorAccent::Shade950, QColor("#121212"));
        p->setColor(ColorAccent::ContrastDark, QColor("#121212"));
        p->setColor(ColorAccent::ContrastLight, QColor("#fcfcfc"));
        p->setColor(ColorAccent::Contrast50, QColor("#121212"));
        p->setColor(ColorAccent::Contrast100, QColor("#121212"));
        p->setColor(ColorAccent::Contrast200, QColor("#121212"));
        p->setColor(ColorAccent::Contrast300, QColor("#121212"));
        p->setColor(ColorAccent::Contrast400, QColor("#fcfcfc"));
        p->setColor(ColorAccent::Contrast500, QColor("#fcfcfc"));
        p->setColor(ColorAccent::Contrast600, QColor("#fcfcfc"));
        p->setColor(ColorAccent::Contrast700, QColor("#fcfcfc"));
        p->setColor(ColorAccent::Contrast800, QColor("#fcfcfc"));
        p->setColor(ColorAccent::Contrast900, QColor("#fcfcfc"));
        p->setColor(ColorAccent::Contrast950, QColor("#fcfcfc"));
    }

    // Primitives
    primitives->setSpacing(4.0);
    primitives->setTextScaling(1.067);
    primitives->setRadiusBase(4.0);
    primitives->setRadiusContainer(4.0);
    primitives->setBorderWidth(1.0);
    primitives->setDivideWidth(1.0);
    primitives->setRingWidth(1.0);
    primitives->setBodyBackgroundColor(QColor("#fcfcfc"));
    primitives->setBodyBackgroundColorDark(QColor("#121212"));

    // base typography
    {
        auto *typo = primitives->baseFont();
        typo->setFontFamily(QStringLiteral("system-ui"));
        typo->setFontWeight(400);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#121212"));
        typo->setFontColorDark(QColor("#fcfcfc"));
    }

    // heading typography
    {
        auto *typo = primitives->headingFont();
        typo->setFontWeight(700);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#121212"));
        typo->setFontColorDark(QColor("#fcfcfc"));
    }

    // anchor typography
    {
        auto *typo = primitives->anchorFont();
        typo->setFontWeight(-1);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#d4e6ff"));
        typo->setFontColorDark(QColor("#2787f8"));
    }
}

void applyConcord(ColorSchema *colors, PrimitiveSchema *primitives) {
    // primary
    {
        auto *p = colors->palette(ColorVariant::Primary);
        p->setColor(ColorAccent::Shade50, QColor("#e5eaff"));
        p->setColor(ColorAccent::Shade100, QColor("#c9cffa"));
        p->setColor(ColorAccent::Shade200, QColor("#adb5fb"));
        p->setColor(ColorAccent::Shade300, QColor("#8f99fa"));
        p->setColor(ColorAccent::Shade400, QColor("#7480f3"));
        p->setColor(ColorAccent::Shade500, QColor("#5865f2"));
        p->setColor(ColorAccent::Shade600, QColor("#4e5ae7"));
        p->setColor(ColorAccent::Shade700, QColor("#444eda"));
        p->setColor(ColorAccent::Shade800, QColor("#3b44cf"));
        p->setColor(ColorAccent::Shade900, QColor("#3138c3"));
        p->setColor(ColorAccent::Shade950, QColor("#272db8"));
        p->setColor(ColorAccent::ContrastDark, QColor("#272db8"));
        p->setColor(ColorAccent::ContrastLight, QColor("#e5eaff"));
        p->setColor(ColorAccent::Contrast50, QColor("#272db8"));
        p->setColor(ColorAccent::Contrast100, QColor("#272db8"));
        p->setColor(ColorAccent::Contrast200, QColor("#272db8"));
        p->setColor(ColorAccent::Contrast300, QColor("#272db8"));
        p->setColor(ColorAccent::Contrast400, QColor("#272db8"));
        p->setColor(ColorAccent::Contrast500, QColor("#e5eaff"));
        p->setColor(ColorAccent::Contrast600, QColor("#e5eaff"));
        p->setColor(ColorAccent::Contrast700, QColor("#e5eaff"));
        p->setColor(ColorAccent::Contrast800, QColor("#e5eaff"));
        p->setColor(ColorAccent::Contrast900, QColor("#e5eaff"));
        p->setColor(ColorAccent::Contrast950, QColor("#e5eaff"));
    }
    // secondary
    {
        auto *p = colors->palette(ColorVariant::Secondary);
        p->setColor(ColorAccent::Shade50, QColor("#ffcaff"));
        p->setColor(ColorAccent::Shade100, QColor("#fb9cd1"));
        p->setColor(ColorAccent::Shade200, QColor("#f588c3"));
        p->setColor(ColorAccent::Shade300, QColor("#f470b8"));
        p->setColor(ColorAccent::Shade400, QColor("#f05aab"));
        p->setColor(ColorAccent::Shade500, QColor("#ec439e"));
        p->setColor(ColorAccent::Shade600, QColor("#ce428c"));
        p->setColor(ColorAccent::Shade700, QColor("#b4397a"));
        p->setColor(ColorAccent::Shade800, QColor("#9a3168"));
        p->setColor(ColorAccent::Shade900, QColor("#7d2d56"));
        p->setColor(ColorAccent::Shade950, QColor("#592741"));
        p->setColor(ColorAccent::ContrastDark, QColor("#592741"));
        p->setColor(ColorAccent::ContrastLight, QColor("#ffcaff"));
        p->setColor(ColorAccent::Contrast50, QColor("#592741"));
        p->setColor(ColorAccent::Contrast100, QColor("#592741"));
        p->setColor(ColorAccent::Contrast200, QColor("#592741"));
        p->setColor(ColorAccent::Contrast300, QColor("#592741"));
        p->setColor(ColorAccent::Contrast400, QColor("#592741"));
        p->setColor(ColorAccent::Contrast500, QColor("#592741"));
        p->setColor(ColorAccent::Contrast600, QColor("#ffcaff"));
        p->setColor(ColorAccent::Contrast700, QColor("#ffcaff"));
        p->setColor(ColorAccent::Contrast800, QColor("#ffcaff"));
        p->setColor(ColorAccent::Contrast900, QColor("#ffcaff"));
        p->setColor(ColorAccent::Contrast950, QColor("#ffcaff"));
    }
    // tertiary
    {
        auto *p = colors->palette(ColorVariant::Tertiary);
        p->setColor(ColorAccent::Shade50, QColor("#cbe6fb"));
        p->setColor(ColorAccent::Shade100, QColor("#b2d9f8"));
        p->setColor(ColorAccent::Shade200, QColor("#99cbf5"));
        p->setColor(ColorAccent::Shade300, QColor("#7fbef3"));
        p->setColor(ColorAccent::Shade400, QColor("#5fb0f6"));
        p->setColor(ColorAccent::Shade500, QColor("#44a3f5"));
        p->setColor(ColorAccent::Shade600, QColor("#3f93df"));
        p->setColor(ColorAccent::Shade700, QColor("#3382cf"));
        p->setColor(ColorAccent::Shade800, QColor("#2d72b9"));
        p->setColor(ColorAccent::Shade900, QColor("#2261a8"));
        p->setColor(ColorAccent::Shade950, QColor("#1d5192"));
        p->setColor(ColorAccent::ContrastDark, QColor("#1d5192"));
        p->setColor(ColorAccent::ContrastLight, QColor("#cbe6fb"));
        p->setColor(ColorAccent::Contrast50, QColor("#1d5192"));
        p->setColor(ColorAccent::Contrast100, QColor("#1d5192"));
        p->setColor(ColorAccent::Contrast200, QColor("#1d5192"));
        p->setColor(ColorAccent::Contrast300, QColor("#1d5192"));
        p->setColor(ColorAccent::Contrast400, QColor("#1d5192"));
        p->setColor(ColorAccent::Contrast500, QColor("#1d5192"));
        p->setColor(ColorAccent::Contrast600, QColor("#1d5192"));
        p->setColor(ColorAccent::Contrast700, QColor("#1d5192"));
        p->setColor(ColorAccent::Contrast800, QColor("#1d5192"));
        p->setColor(ColorAccent::Contrast900, QColor("#cbe6fb"));
        p->setColor(ColorAccent::Contrast950, QColor("#cbe6fb"));
    }
    // success
    {
        auto *p = colors->palette(ColorVariant::Success);
        p->setColor(ColorAccent::Shade50, QColor("#e6fff3"));
        p->setColor(ColorAccent::Shade100, QColor("#c7fddc"));
        p->setColor(ColorAccent::Shade200, QColor("#aef9c9"));
        p->setColor(ColorAccent::Shade300, QColor("#8df8b1"));
        p->setColor(ColorAccent::Shade400, QColor("#72f59c"));
        p->setColor(ColorAccent::Shade500, QColor("#53f286"));
        p->setColor(ColorAccent::Shade600, QColor("#48d971"));
        p->setColor(ColorAccent::Shade700, QColor("#2ec157"));
        p->setColor(ColorAccent::Shade800, QColor("#21a640"));
        p->setColor(ColorAccent::Shade900, QColor("#118d2a"));
        p->setColor(ColorAccent::Shade950, QColor("#007411"));
        p->setColor(ColorAccent::ContrastDark, QColor("#007411"));
        p->setColor(ColorAccent::ContrastLight, QColor("#e6fff3"));
        p->setColor(ColorAccent::Contrast50, QColor("#007411"));
        p->setColor(ColorAccent::Contrast100, QColor("#007411"));
        p->setColor(ColorAccent::Contrast200, QColor("#007411"));
        p->setColor(ColorAccent::Contrast300, QColor("#007411"));
        p->setColor(ColorAccent::Contrast400, QColor("#007411"));
        p->setColor(ColorAccent::Contrast500, QColor("#007411"));
        p->setColor(ColorAccent::Contrast600, QColor("#007411"));
        p->setColor(ColorAccent::Contrast700, QColor("#007411"));
        p->setColor(ColorAccent::Contrast800, QColor("#007411"));
        p->setColor(ColorAccent::Contrast900, QColor("#007411"));
        p->setColor(ColorAccent::Contrast950, QColor("#e6fff3"));
    }
    // warning
    {
        auto *p = colors->palette(ColorVariant::Warning);
        p->setColor(ColorAccent::Shade50, QColor("#fff7c9"));
        p->setColor(ColorAccent::Shade100, QColor("#fff4b6"));
        p->setColor(ColorAccent::Shade200, QColor("#fff1a2"));
        p->setColor(ColorAccent::Shade300, QColor("#feed8b"));
        p->setColor(ColorAccent::Shade400, QColor("#feea74"));
        p->setColor(ColorAccent::Shade500, QColor("#ffe758"));
        p->setColor(ColorAccent::Shade600, QColor("#e8d14d"));
        p->setColor(ColorAccent::Shade700, QColor("#d3bb30"));
        p->setColor(ColorAccent::Shade800, QColor("#bca523"));
        p->setColor(ColorAccent::Shade900, QColor("#a68f13"));
        p->setColor(ColorAccent::Shade950, QColor("#907900"));
        p->setColor(ColorAccent::ContrastDark, QColor("#907900"));
        p->setColor(ColorAccent::ContrastLight, QColor("#fff7c9"));
        p->setColor(ColorAccent::Contrast50, QColor("#907900"));
        p->setColor(ColorAccent::Contrast100, QColor("#907900"));
        p->setColor(ColorAccent::Contrast200, QColor("#907900"));
        p->setColor(ColorAccent::Contrast300, QColor("#907900"));
        p->setColor(ColorAccent::Contrast400, QColor("#907900"));
        p->setColor(ColorAccent::Contrast500, QColor("#907900"));
        p->setColor(ColorAccent::Contrast600, QColor("#907900"));
        p->setColor(ColorAccent::Contrast700, QColor("#907900"));
        p->setColor(ColorAccent::Contrast800, QColor("#907900"));
        p->setColor(ColorAccent::Contrast900, QColor("#907900"));
        p->setColor(ColorAccent::Contrast950, QColor("#907900"));
    }
    // error
    {
        auto *p = colors->palette(ColorVariant::Error);
        p->setColor(ColorAccent::Shade50, QColor("#ffd5cc"));
        p->setColor(ColorAccent::Shade100, QColor("#fcb8b1"));
        p->setColor(ColorAccent::Shade200, QColor("#f69b97"));
        p->setColor(ColorAccent::Shade300, QColor("#f67c7a"));
        p->setColor(ColorAccent::Shade400, QColor("#f15f60"));
        p->setColor(ColorAccent::Shade500, QColor("#ee4044"));
        p->setColor(ColorAccent::Shade600, QColor("#da373a"));
        p->setColor(ColorAccent::Shade700, QColor("#c72d30"));
        p->setColor(ColorAccent::Shade800, QColor("#af2a2a"));
        p->setColor(ColorAccent::Shade900, QColor("#9c2020"));
        p->setColor(ColorAccent::Shade950, QColor("#891515"));
        p->setColor(ColorAccent::ContrastDark, QColor("#891515"));
        p->setColor(ColorAccent::ContrastLight, QColor("#ffd5cc"));
        p->setColor(ColorAccent::Contrast50, QColor("#891515"));
        p->setColor(ColorAccent::Contrast100, QColor("#891515"));
        p->setColor(ColorAccent::Contrast200, QColor("#891515"));
        p->setColor(ColorAccent::Contrast300, QColor("#891515"));
        p->setColor(ColorAccent::Contrast400, QColor("#891515"));
        p->setColor(ColorAccent::Contrast500, QColor("#891515"));
        p->setColor(ColorAccent::Contrast600, QColor("#891515"));
        p->setColor(ColorAccent::Contrast700, QColor("#ffd5cc"));
        p->setColor(ColorAccent::Contrast800, QColor("#ffd5cc"));
        p->setColor(ColorAccent::Contrast900, QColor("#ffd5cc"));
        p->setColor(ColorAccent::Contrast950, QColor("#ffd5cc"));
    }
    // surface
    {
        auto *p = colors->palette(ColorVariant::Surface);
        p->setColor(ColorAccent::Shade100, QColor("#d7d7d7"));
        p->setColor(ColorAccent::Shade200, QColor("#b9b9c0"));
        p->setColor(ColorAccent::Shade300, QColor("#999ca2"));
        p->setColor(ColorAccent::Shade400, QColor("#7c7e84"));
        p->setColor(ColorAccent::Shade500, QColor("#5f6066"));
        p->setColor(ColorAccent::Shade600, QColor("#515359"));
        p->setColor(ColorAccent::Shade700, QColor("#44464c"));
        p->setColor(ColorAccent::Shade800, QColor("#38383e"));
        p->setColor(ColorAccent::Shade900, QColor("#2b2b30"));
        p->setColor(ColorAccent::Shade950, QColor("#1e1e23"));
        p->setColor(ColorAccent::ContrastDark, QColor("#1e1e23"));
        p->setColor(ColorAccent::ContrastLight, QColor("#ffffff"));
        p->setColor(ColorAccent::Contrast50, QColor("#1e1e23"));
        p->setColor(ColorAccent::Contrast100, QColor("#1e1e23"));
        p->setColor(ColorAccent::Contrast200, QColor("#1e1e23"));
        p->setColor(ColorAccent::Contrast300, QColor("#1e1e23"));
        p->setColor(ColorAccent::Contrast400, QColor("#ffffff"));
        p->setColor(ColorAccent::Contrast500, QColor("#ffffff"));
        p->setColor(ColorAccent::Contrast600, QColor("#ffffff"));
        p->setColor(ColorAccent::Contrast700, QColor("#ffffff"));
        p->setColor(ColorAccent::Contrast800, QColor("#ffffff"));
        p->setColor(ColorAccent::Contrast900, QColor("#ffffff"));
        p->setColor(ColorAccent::Contrast950, QColor("#ffffff"));
    }

    // Primitives
    primitives->setSpacing(4.0);
    primitives->setTextScaling(1.067);
    primitives->setRadiusBase(6.0);
    primitives->setRadiusContainer(12.0);
    primitives->setBorderWidth(1.0);
    primitives->setDivideWidth(1.0);
    primitives->setRingWidth(1.0);
    primitives->setBodyBackgroundColor(QColor("#ffffff"));
    primitives->setBodyBackgroundColorDark(QColor("#1a1a1a"));

    // base typography
    {
        auto *typo = primitives->baseFont();
        typo->setFontFamily(QStringLiteral("system-ui"));
        typo->setFontWeight(400);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#1e1e23"));
        typo->setFontColorDark(QColor("#fafafa"));
    }

    // heading typography
    {
        auto *typo = primitives->headingFont();
        typo->setFontFamily(QStringLiteral("Seravek"));
        typo->setFontWeight(700);
        typo->setItalic(false);
        typo->setLetterSpacing(0.025);
        typo->setFontColor(QColor("#1e1e23"));
        typo->setFontColorDark(QColor("#fafafa"));
    }

    // anchor typography
    {
        auto *typo = primitives->anchorFont();
        typo->setFontWeight(-1);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#3f93df"));
        typo->setFontColorDark(QColor("#cbe6fb"));
    }
}

void applyCrimson(ColorSchema *colors, PrimitiveSchema *primitives) {
    // primary
    {
        auto *p = colors->palette(ColorVariant::Primary);
        p->setColor(ColorAccent::Shade50, QColor("#f8cdd6"));
        p->setColor(ColorAccent::Shade100, QColor("#f3a8b7"));
        p->setColor(ColorAccent::Shade200, QColor("#ec8398"));
        p->setColor(ColorAccent::Shade300, QColor("#e55d79"));
        p->setColor(ColorAccent::Shade400, QColor("#dd385a"));
        p->setColor(ColorAccent::Shade500, QColor("#d21d3d"));
        p->setColor(ColorAccent::Shade600, QColor("#bd0b33"));
        p->setColor(ColorAccent::Shade700, QColor("#a50b2d"));
        p->setColor(ColorAccent::Shade800, QColor("#8d0825"));
        p->setColor(ColorAccent::Shade900, QColor("#76061e"));
        p->setColor(ColorAccent::Shade950, QColor("#5d0217"));
        p->setColor(ColorAccent::ContrastDark, QColor("#5d0217"));
        p->setColor(ColorAccent::ContrastLight, QColor("#f8cdd6"));
        p->setColor(ColorAccent::Contrast50, QColor("#5d0217"));
        p->setColor(ColorAccent::Contrast100, QColor("#5d0217"));
        p->setColor(ColorAccent::Contrast200, QColor("#5d0217"));
        p->setColor(ColorAccent::Contrast300, QColor("#5d0217"));
        p->setColor(ColorAccent::Contrast400, QColor("#5d0217"));
        p->setColor(ColorAccent::Contrast500, QColor("#f8cdd6"));
        p->setColor(ColorAccent::Contrast600, QColor("#f8cdd6"));
        p->setColor(ColorAccent::Contrast700, QColor("#f8cdd6"));
        p->setColor(ColorAccent::Contrast800, QColor("#f8cdd6"));
        p->setColor(ColorAccent::Contrast900, QColor("#f8cdd6"));
        p->setColor(ColorAccent::Contrast950, QColor("#f8cdd6"));
    }
    // secondary
    {
        auto *p = colors->palette(ColorVariant::Secondary);
        p->setColor(ColorAccent::Shade50, QColor("#d3ebf7"));
        p->setColor(ColorAccent::Shade100, QColor("#b8d6e8"));
        p->setColor(ColorAccent::Shade200, QColor("#9dc2d8"));
        p->setColor(ColorAccent::Shade300, QColor("#7dadce"));
        p->setColor(ColorAccent::Shade400, QColor("#6299be"));
        p->setColor(ColorAccent::Shade500, QColor("#4785ae"));
        p->setColor(ColorAccent::Shade600, QColor("#407699"));
        p->setColor(ColorAccent::Shade700, QColor("#31678a"));
        p->setColor(ColorAccent::Shade800, QColor("#2a5775"));
        p->setColor(ColorAccent::Shade900, QColor("#234861"));
        p->setColor(ColorAccent::Shade950, QColor("#1a394c"));
        p->setColor(ColorAccent::ContrastDark, QColor("#1a394c"));
        p->setColor(ColorAccent::ContrastLight, QColor("#d3ebf7"));
        p->setColor(ColorAccent::Contrast50, QColor("#1a394c"));
        p->setColor(ColorAccent::Contrast100, QColor("#1a394c"));
        p->setColor(ColorAccent::Contrast200, QColor("#1a394c"));
        p->setColor(ColorAccent::Contrast300, QColor("#1a394c"));
        p->setColor(ColorAccent::Contrast400, QColor("#1a394c"));
        p->setColor(ColorAccent::Contrast500, QColor("#d3ebf7"));
        p->setColor(ColorAccent::Contrast600, QColor("#d3ebf7"));
        p->setColor(ColorAccent::Contrast700, QColor("#d3ebf7"));
        p->setColor(ColorAccent::Contrast800, QColor("#d3ebf7"));
        p->setColor(ColorAccent::Contrast900, QColor("#d3ebf7"));
        p->setColor(ColorAccent::Contrast950, QColor("#d3ebf7"));
    }
    // tertiary
    {
        auto *p = colors->palette(ColorVariant::Tertiary);
        p->setColor(ColorAccent::Shade50, QColor("#f5f5f5"));
        p->setColor(ColorAccent::Shade100, QColor("#f1f1f1"));
        p->setColor(ColorAccent::Shade200, QColor("#ededed"));
        p->setColor(ColorAccent::Shade300, QColor("#e3e3e3"));
        p->setColor(ColorAccent::Shade400, QColor("#d4ccca"));
        p->setColor(ColorAccent::Shade500, QColor("#bfb6b5"));
        p->setColor(ColorAccent::Shade600, QColor("#aca4a2"));
        p->setColor(ColorAccent::Shade700, QColor("#918987"));
        p->setColor(ColorAccent::Shade800, QColor("#746d6b"));
        p->setColor(ColorAccent::Shade900, QColor("#605857"));
        p->setColor(ColorAccent::Shade950, QColor("#574f4e"));
        p->setColor(ColorAccent::ContrastDark, QColor("#574f4e"));
        p->setColor(ColorAccent::ContrastLight, QColor("#f5f5f5"));
        p->setColor(ColorAccent::Contrast50, QColor("#574f4e"));
        p->setColor(ColorAccent::Contrast100, QColor("#574f4e"));
        p->setColor(ColorAccent::Contrast200, QColor("#574f4e"));
        p->setColor(ColorAccent::Contrast300, QColor("#574f4e"));
        p->setColor(ColorAccent::Contrast400, QColor("#574f4e"));
        p->setColor(ColorAccent::Contrast500, QColor("#574f4e"));
        p->setColor(ColorAccent::Contrast600, QColor("#574f4e"));
        p->setColor(ColorAccent::Contrast700, QColor("#f5f5f5"));
        p->setColor(ColorAccent::Contrast800, QColor("#f5f5f5"));
        p->setColor(ColorAccent::Contrast900, QColor("#f5f5f5"));
        p->setColor(ColorAccent::Contrast950, QColor("#f5f5f5"));
    }
    // success
    {
        auto *p = colors->palette(ColorVariant::Success);
        p->setColor(ColorAccent::Shade50, QColor("#f5fbec"));
        p->setColor(ColorAccent::Shade100, QColor("#f3f8ea"));
        p->setColor(ColorAccent::Shade200, QColor("#f1f6e8"));
        p->setColor(ColorAccent::Shade300, QColor("#e6f1d4"));
        p->setColor(ColorAccent::Shade400, QColor("#d4e7b5"));
        p->setColor(ColorAccent::Shade500, QColor("#c1dd95"));
        p->setColor(ColorAccent::Shade600, QColor("#aec787"));
        p->setColor(ColorAccent::Shade700, QColor("#91a66f"));
        p->setColor(ColorAccent::Shade800, QColor("#75855d"));
        p->setColor(ColorAccent::Shade900, QColor("#5f6c4c"));
        p->setColor(ColorAccent::Shade950, QColor("#566344"));
        p->setColor(ColorAccent::ContrastDark, QColor("#566344"));
        p->setColor(ColorAccent::ContrastLight, QColor("#f5fbec"));
        p->setColor(ColorAccent::Contrast50, QColor("#566344"));
        p->setColor(ColorAccent::Contrast100, QColor("#566344"));
        p->setColor(ColorAccent::Contrast200, QColor("#566344"));
        p->setColor(ColorAccent::Contrast300, QColor("#566344"));
        p->setColor(ColorAccent::Contrast400, QColor("#566344"));
        p->setColor(ColorAccent::Contrast500, QColor("#566344"));
        p->setColor(ColorAccent::Contrast600, QColor("#566344"));
        p->setColor(ColorAccent::Contrast700, QColor("#f5fbec"));
        p->setColor(ColorAccent::Contrast800, QColor("#f5fbec"));
        p->setColor(ColorAccent::Contrast900, QColor("#f5fbec"));
        p->setColor(ColorAccent::Contrast950, QColor("#f5fbec"));
    }
    // warning
    {
        auto *p = colors->palette(ColorVariant::Warning);
        p->setColor(ColorAccent::Shade50, QColor("#fbf6e7"));
        p->setColor(ColorAccent::Shade100, QColor("#fbf3dd"));
        p->setColor(ColorAccent::Shade200, QColor("#f7f0da"));
        p->setColor(ColorAccent::Shade300, QColor("#f3e7c2"));
        p->setColor(ColorAccent::Shade400, QColor("#ebd490"));
        p->setColor(ColorAccent::Shade500, QColor("#e5c258"));
        p->setColor(ColorAccent::Shade600, QColor("#ccaf5a"));
        p->setColor(ColorAccent::Shade700, QColor("#ab9246"));
        p->setColor(ColorAccent::Shade800, QColor("#88743b"));
        p->setColor(ColorAccent::Shade900, QColor("#705f2f"));
        p->setColor(ColorAccent::Shade950, QColor("#675626"));
        p->setColor(ColorAccent::ContrastDark, QColor("#675626"));
        p->setColor(ColorAccent::ContrastLight, QColor("#fbf6e7"));
        p->setColor(ColorAccent::Contrast50, QColor("#675626"));
        p->setColor(ColorAccent::Contrast100, QColor("#675626"));
        p->setColor(ColorAccent::Contrast200, QColor("#675626"));
        p->setColor(ColorAccent::Contrast300, QColor("#675626"));
        p->setColor(ColorAccent::Contrast400, QColor("#675626"));
        p->setColor(ColorAccent::Contrast500, QColor("#675626"));
        p->setColor(ColorAccent::Contrast600, QColor("#675626"));
        p->setColor(ColorAccent::Contrast700, QColor("#fbf6e7"));
        p->setColor(ColorAccent::Contrast800, QColor("#fbf6e7"));
        p->setColor(ColorAccent::Contrast900, QColor("#fbf6e7"));
        p->setColor(ColorAccent::Contrast950, QColor("#fbf6e7"));
    }
    // error
    {
        auto *p = colors->palette(ColorVariant::Error);
        p->setColor(ColorAccent::Shade50, QColor("#f6eded"));
        p->setColor(ColorAccent::Shade100, QColor("#f7e5e6"));
        p->setColor(ColorAccent::Shade200, QColor("#f2e0e1"));
        p->setColor(ColorAccent::Shade300, QColor("#efcbcc"));
        p->setColor(ColorAccent::Shade400, QColor("#e0a5a7"));
        p->setColor(ColorAccent::Shade500, QColor("#d08082"));
        p->setColor(ColorAccent::Shade600, QColor("#bf7073"));
        p->setColor(ColorAccent::Shade700, QColor("#9d6062"));
        p->setColor(ColorAccent::Shade800, QColor("#7f4b4d"));
        p->setColor(ColorAccent::Shade900, QColor("#683d3f"));
        p->setColor(ColorAccent::Shade950, QColor("#5f3536"));
        p->setColor(ColorAccent::ContrastDark, QColor("#5f3536"));
        p->setColor(ColorAccent::ContrastLight, QColor("#f6eded"));
        p->setColor(ColorAccent::Contrast50, QColor("#5f3536"));
        p->setColor(ColorAccent::Contrast100, QColor("#5f3536"));
        p->setColor(ColorAccent::Contrast200, QColor("#5f3536"));
        p->setColor(ColorAccent::Contrast300, QColor("#5f3536"));
        p->setColor(ColorAccent::Contrast400, QColor("#5f3536"));
        p->setColor(ColorAccent::Contrast500, QColor("#5f3536"));
        p->setColor(ColorAccent::Contrast600, QColor("#f6eded"));
        p->setColor(ColorAccent::Contrast700, QColor("#f6eded"));
        p->setColor(ColorAccent::Contrast800, QColor("#f6eded"));
        p->setColor(ColorAccent::Contrast900, QColor("#f6eded"));
        p->setColor(ColorAccent::Contrast950, QColor("#f6eded"));
    }
    // surface
    {
        auto *p = colors->palette(ColorVariant::Surface);
        p->setColor(ColorAccent::Shade50, QColor("#e0e0e0"));
        p->setColor(ColorAccent::Shade100, QColor("#bcbfc6"));
        p->setColor(ColorAccent::Shade200, QColor("#9c9ea5"));
        p->setColor(ColorAccent::Shade300, QColor("#7a7c89"));
        p->setColor(ColorAccent::Shade400, QColor("#585b6d"));
        p->setColor(ColorAccent::Shade500, QColor("#353a50"));
        p->setColor(ColorAccent::Shade600, QColor("#2e3142"));
        p->setColor(ColorAccent::Shade700, QColor("#252838"));
        p->setColor(ColorAccent::Shade800, QColor("#1d202f"));
        p->setColor(ColorAccent::Shade900, QColor("#151721"));
        p->setColor(ColorAccent::Shade950, QColor("#0c0e17"));
        p->setColor(ColorAccent::ContrastDark, QColor("#0c0e17"));
        p->setColor(ColorAccent::ContrastLight, QColor("#e0e0e0"));
        p->setColor(ColorAccent::Contrast50, QColor("#0c0e17"));
        p->setColor(ColorAccent::Contrast100, QColor("#0c0e17"));
        p->setColor(ColorAccent::Contrast200, QColor("#0c0e17"));
        p->setColor(ColorAccent::Contrast300, QColor("#0c0e17"));
        p->setColor(ColorAccent::Contrast400, QColor("#e0e0e0"));
        p->setColor(ColorAccent::Contrast500, QColor("#e0e0e0"));
        p->setColor(ColorAccent::Contrast600, QColor("#e0e0e0"));
        p->setColor(ColorAccent::Contrast700, QColor("#e0e0e0"));
        p->setColor(ColorAccent::Contrast800, QColor("#e0e0e0"));
        p->setColor(ColorAccent::Contrast900, QColor("#e0e0e0"));
        p->setColor(ColorAccent::Contrast950, QColor("#e0e0e0"));
    }

    // Primitives
    primitives->setSpacing(4.0);
    primitives->setTextScaling(1.067);
    primitives->setRadiusBase(6.0);
    primitives->setRadiusContainer(12.0);
    primitives->setBorderWidth(1.0);
    primitives->setDivideWidth(1.0);
    primitives->setRingWidth(1.0);
    primitives->setBodyBackgroundColor(QColor("#ffffff"));
    primitives->setBodyBackgroundColorDark(QColor("#0c0e17"));

    // base typography
    {
        auto *typo = primitives->baseFont();
        typo->setFontFamily(QStringLiteral("Avenir"));
        typo->setFontWeight(400);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#0c0e17"));
        typo->setFontColorDark(QColor("#e0e0e0"));
    }

    // heading typography
    {
        auto *typo = primitives->headingFont();
        typo->setFontFamily(QStringLiteral("Avenir"));
        typo->setFontWeight(400);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#0c0e17"));
        typo->setFontColorDark(QColor("#e0e0e0"));
    }

    // anchor typography
    {
        auto *typo = primitives->anchorFont();
        typo->setFontWeight(-1);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#f8cdd6"));
        typo->setFontColorDark(QColor("#f8cdd6"));
    }
}

void applyFennec(ColorSchema *colors, PrimitiveSchema *primitives) {
    // primary
    {
        auto *p = colors->palette(ColorVariant::Primary);
        p->setColor(ColorAccent::Shade50, QColor("#fae2b9"));
        p->setColor(ColorAccent::Shade100, QColor("#fbc592"));
        p->setColor(ColorAccent::Shade200, QColor("#f9a86f"));
        p->setColor(ColorAccent::Shade300, QColor("#f78c50"));
        p->setColor(ColorAccent::Shade400, QColor("#fa6c23"));
        p->setColor(ColorAccent::Shade500, QColor("#f6530d"));
        p->setColor(ColorAccent::Shade600, QColor("#de4403"));
        p->setColor(ColorAccent::Shade700, QColor("#c33a12"));
        p->setColor(ColorAccent::Shade800, QColor("#a9311b"));
        p->setColor(ColorAccent::Shade900, QColor("#8e2722"));
        p->setColor(ColorAccent::Shade950, QColor("#771726"));
        p->setColor(ColorAccent::ContrastDark, QColor("#771726"));
        p->setColor(ColorAccent::ContrastLight, QColor("#fae2b9"));
        p->setColor(ColorAccent::Contrast50, QColor("#771726"));
        p->setColor(ColorAccent::Contrast100, QColor("#771726"));
        p->setColor(ColorAccent::Contrast200, QColor("#771726"));
        p->setColor(ColorAccent::Contrast300, QColor("#771726"));
        p->setColor(ColorAccent::Contrast400, QColor("#771726"));
        p->setColor(ColorAccent::Contrast500, QColor("#771726"));
        p->setColor(ColorAccent::Contrast600, QColor("#fae2b9"));
        p->setColor(ColorAccent::Contrast700, QColor("#fae2b9"));
        p->setColor(ColorAccent::Contrast800, QColor("#fae2b9"));
        p->setColor(ColorAccent::Contrast900, QColor("#fae2b9"));
        p->setColor(ColorAccent::Contrast950, QColor("#fae2b9"));
    }
    // secondary
    {
        auto *p = colors->palette(ColorVariant::Secondary);
        p->setColor(ColorAccent::Shade50, QColor("#fef2dd"));
        p->setColor(ColorAccent::Shade100, QColor("#ffebc9"));
        p->setColor(ColorAccent::Shade200, QColor("#fee3bb"));
        p->setColor(ColorAccent::Shade300, QColor("#fddcae"));
        p->setColor(ColorAccent::Shade400, QColor("#fbd4a0"));
        p->setColor(ColorAccent::Shade500, QColor("#fecd8a"));
        p->setColor(ColorAccent::Shade600, QColor("#e0b87c"));
        p->setColor(ColorAccent::Shade700, QColor("#c7a265"));
        p->setColor(ColorAccent::Shade800, QColor("#ad8d4e"));
        p->setColor(ColorAccent::Shade900, QColor("#947737"));
        p->setColor(ColorAccent::Shade950, QColor("#7a621e"));
        p->setColor(ColorAccent::ContrastDark, QColor("#7a621e"));
        p->setColor(ColorAccent::ContrastLight, QColor("#fef2dd"));
        p->setColor(ColorAccent::Contrast50, QColor("#7a621e"));
        p->setColor(ColorAccent::Contrast100, QColor("#7a621e"));
        p->setColor(ColorAccent::Contrast200, QColor("#7a621e"));
        p->setColor(ColorAccent::Contrast300, QColor("#7a621e"));
        p->setColor(ColorAccent::Contrast400, QColor("#7a621e"));
        p->setColor(ColorAccent::Contrast500, QColor("#7a621e"));
        p->setColor(ColorAccent::Contrast600, QColor("#7a621e"));
        p->setColor(ColorAccent::Contrast700, QColor("#7a621e"));
        p->setColor(ColorAccent::Contrast800, QColor("#fef2dd"));
        p->setColor(ColorAccent::Contrast900, QColor("#fef2dd"));
        p->setColor(ColorAccent::Contrast950, QColor("#fef2dd"));
    }
    // tertiary
    {
        auto *p = colors->palette(ColorVariant::Tertiary);
        p->setColor(ColorAccent::Shade50, QColor("#ebfefe"));
        p->setColor(ColorAccent::Shade100, QColor("#cae6e5"));
        p->setColor(ColorAccent::Shade200, QColor("#b0ccca"));
        p->setColor(ColorAccent::Shade300, QColor("#90b4b0"));
        p->setColor(ColorAccent::Shade400, QColor("#769a96"));
        p->setColor(ColorAccent::Shade500, QColor("#55827c"));
        p->setColor(ColorAccent::Shade600, QColor("#477471"));
        p->setColor(ColorAccent::Shade700, QColor("#396767"));
        p->setColor(ColorAccent::Shade800, QColor("#35575b"));
        p->setColor(ColorAccent::Shade900, QColor("#294950"));
        p->setColor(ColorAccent::Shade950, QColor("#1d3b45"));
        p->setColor(ColorAccent::ContrastDark, QColor("#1d3b45"));
        p->setColor(ColorAccent::ContrastLight, QColor("#ebfefe"));
        p->setColor(ColorAccent::Contrast50, QColor("#1d3b45"));
        p->setColor(ColorAccent::Contrast100, QColor("#1d3b45"));
        p->setColor(ColorAccent::Contrast200, QColor("#1d3b45"));
        p->setColor(ColorAccent::Contrast300, QColor("#1d3b45"));
        p->setColor(ColorAccent::Contrast400, QColor("#1d3b45"));
        p->setColor(ColorAccent::Contrast500, QColor("#ebfefe"));
        p->setColor(ColorAccent::Contrast600, QColor("#ebfefe"));
        p->setColor(ColorAccent::Contrast700, QColor("#ebfefe"));
        p->setColor(ColorAccent::Contrast800, QColor("#ebfefe"));
        p->setColor(ColorAccent::Contrast900, QColor("#ebfefe"));
        p->setColor(ColorAccent::Contrast950, QColor("#ebfefe"));
    }
    // success
    {
        auto *p = colors->palette(ColorVariant::Success);
        p->setColor(ColorAccent::Shade50, QColor("#d2ffcf"));
        p->setColor(ColorAccent::Shade100, QColor("#caf4c2"));
        p->setColor(ColorAccent::Shade200, QColor("#bdeab1"));
        p->setColor(ColorAccent::Shade300, QColor("#b0df9f"));
        p->setColor(ColorAccent::Shade400, QColor("#a4d68e"));
        p->setColor(ColorAccent::Shade500, QColor("#98cc7d"));
        p->setColor(ColorAccent::Shade600, QColor("#80b466"));
        p->setColor(ColorAccent::Shade700, QColor("#699d50"));
        p->setColor(ColorAccent::Shade800, QColor("#51853a"));
        p->setColor(ColorAccent::Shade900, QColor("#3a6e23"));
        p->setColor(ColorAccent::Shade950, QColor("#205608"));
        p->setColor(ColorAccent::ContrastDark, QColor("#205608"));
        p->setColor(ColorAccent::ContrastLight, QColor("#d2ffcf"));
        p->setColor(ColorAccent::Contrast50, QColor("#205608"));
        p->setColor(ColorAccent::Contrast100, QColor("#205608"));
        p->setColor(ColorAccent::Contrast200, QColor("#205608"));
        p->setColor(ColorAccent::Contrast300, QColor("#205608"));
        p->setColor(ColorAccent::Contrast400, QColor("#205608"));
        p->setColor(ColorAccent::Contrast500, QColor("#205608"));
        p->setColor(ColorAccent::Contrast600, QColor("#205608"));
        p->setColor(ColorAccent::Contrast700, QColor("#d2ffcf"));
        p->setColor(ColorAccent::Contrast800, QColor("#d2ffcf"));
        p->setColor(ColorAccent::Contrast900, QColor("#d2ffcf"));
        p->setColor(ColorAccent::Contrast950, QColor("#d2ffcf"));
    }
    // warning
    {
        auto *p = colors->palette(ColorVariant::Warning);
        p->setColor(ColorAccent::Shade50, QColor("#f8fbdd"));
        p->setColor(ColorAccent::Shade100, QColor("#f0f1cb"));
        p->setColor(ColorAccent::Shade200, QColor("#e9e7b1"));
        p->setColor(ColorAccent::Shade300, QColor("#e1de98"));
        p->setColor(ColorAccent::Shade400, QColor("#dad485"));
        p->setColor(ColorAccent::Shade500, QColor("#d2ca72"));
        p->setColor(ColorAccent::Shade600, QColor("#b9b35c"));
        p->setColor(ColorAccent::Shade700, QColor("#a19c44"));
        p->setColor(ColorAccent::Shade800, QColor("#88842a"));
        p->setColor(ColorAccent::Shade900, QColor("#706d1c"));
        p->setColor(ColorAccent::Shade950, QColor("#575600"));
        p->setColor(ColorAccent::ContrastDark, QColor("#575600"));
        p->setColor(ColorAccent::ContrastLight, QColor("#f8fbdd"));
        p->setColor(ColorAccent::Contrast50, QColor("#575600"));
        p->setColor(ColorAccent::Contrast100, QColor("#575600"));
        p->setColor(ColorAccent::Contrast200, QColor("#575600"));
        p->setColor(ColorAccent::Contrast300, QColor("#575600"));
        p->setColor(ColorAccent::Contrast400, QColor("#575600"));
        p->setColor(ColorAccent::Contrast500, QColor("#575600"));
        p->setColor(ColorAccent::Contrast600, QColor("#575600"));
        p->setColor(ColorAccent::Contrast700, QColor("#f8fbdd"));
        p->setColor(ColorAccent::Contrast800, QColor("#f8fbdd"));
        p->setColor(ColorAccent::Contrast900, QColor("#f8fbdd"));
        p->setColor(ColorAccent::Contrast950, QColor("#f8fbdd"));
    }
    // error
    {
        auto *p = colors->palette(ColorVariant::Error);
        p->setColor(ColorAccent::Shade100, QColor("#f5edf0"));
        p->setColor(ColorAccent::Shade200, QColor("#f1d8e1"));
        p->setColor(ColorAccent::Shade300, QColor("#e7c6d2"));
        p->setColor(ColorAccent::Shade400, QColor("#e3b2c3"));
        p->setColor(ColorAccent::Shade500, QColor("#d8a1b4"));
        p->setColor(ColorAccent::Shade600, QColor("#c08a9d"));
        p->setColor(ColorAccent::Shade700, QColor("#a87487"));
        p->setColor(ColorAccent::Shade800, QColor("#8f5d70"));
        p->setColor(ColorAccent::Shade900, QColor("#77475a"));
        p->setColor(ColorAccent::Shade950, QColor("#5f3143"));
        p->setColor(ColorAccent::ContrastDark, QColor("#5f3143"));
        p->setColor(ColorAccent::ContrastLight, QColor("#ffffff"));
        p->setColor(ColorAccent::Contrast50, QColor("#5f3143"));
        p->setColor(ColorAccent::Contrast100, QColor("#5f3143"));
        p->setColor(ColorAccent::Contrast200, QColor("#5f3143"));
        p->setColor(ColorAccent::Contrast300, QColor("#5f3143"));
        p->setColor(ColorAccent::Contrast400, QColor("#5f3143"));
        p->setColor(ColorAccent::Contrast500, QColor("#5f3143"));
        p->setColor(ColorAccent::Contrast600, QColor("#ffffff"));
        p->setColor(ColorAccent::Contrast700, QColor("#ffffff"));
        p->setColor(ColorAccent::Contrast800, QColor("#ffffff"));
        p->setColor(ColorAccent::Contrast900, QColor("#ffffff"));
        p->setColor(ColorAccent::Contrast950, QColor("#ffffff"));
    }
    // surface
    {
        auto *p = colors->palette(ColorVariant::Surface);
        p->setColor(ColorAccent::Shade50, QColor("#b9c0bc"));
        p->setColor(ColorAccent::Shade100, QColor("#a4aba8"));
        p->setColor(ColorAccent::Shade200, QColor("#8f9795"));
        p->setColor(ColorAccent::Shade300, QColor("#7a8381"));
        p->setColor(ColorAccent::Shade400, QColor("#666e6e"));
        p->setColor(ColorAccent::Shade500, QColor("#52595b"));
        p->setColor(ColorAccent::Shade600, QColor("#484e51"));
        p->setColor(ColorAccent::Shade700, QColor("#3e4347"));
        p->setColor(ColorAccent::Shade800, QColor("#35383d"));
        p->setColor(ColorAccent::Shade900, QColor("#2b2d32"));
        p->setColor(ColorAccent::Shade950, QColor("#212227"));
        p->setColor(ColorAccent::ContrastDark, QColor("#212227"));
        p->setColor(ColorAccent::ContrastLight, QColor("#b9c0bc"));
        p->setColor(ColorAccent::Contrast50, QColor("#212227"));
        p->setColor(ColorAccent::Contrast100, QColor("#212227"));
        p->setColor(ColorAccent::Contrast200, QColor("#212227"));
        p->setColor(ColorAccent::Contrast300, QColor("#212227"));
        p->setColor(ColorAccent::Contrast400, QColor("#b9c0bc"));
        p->setColor(ColorAccent::Contrast500, QColor("#b9c0bc"));
        p->setColor(ColorAccent::Contrast600, QColor("#b9c0bc"));
        p->setColor(ColorAccent::Contrast700, QColor("#b9c0bc"));
        p->setColor(ColorAccent::Contrast800, QColor("#b9c0bc"));
        p->setColor(ColorAccent::Contrast900, QColor("#b9c0bc"));
        p->setColor(ColorAccent::Contrast950, QColor("#b9c0bc"));
    }

    // Primitives
    primitives->setSpacing(4.0);
    primitives->setTextScaling(1.067);
    primitives->setRadiusBase(6.0);
    primitives->setRadiusContainer(12.0);
    primitives->setBorderWidth(1.0);
    primitives->setDivideWidth(1.0);
    primitives->setRingWidth(1.0);
    primitives->setBodyBackgroundColor(QColor("#b9c0bc"));
    primitives->setBodyBackgroundColorDark(QColor("#212227"));

    // base typography
    {
        auto *typo = primitives->baseFont();
        typo->setFontFamily(QStringLiteral("Bahnschrift"));
        typo->setFontWeight(400);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#000000"));
        typo->setFontColorDark(QColor("#ffffff"));
    }

    // heading typography
    {
        auto *typo = primitives->headingFont();
        typo->setFontFamily(QStringLiteral("Bahnschrift"));
        typo->setFontWeight(400);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#000000"));
        typo->setFontColorDark(QColor("#fef2dd"));
    }

    // anchor typography
    {
        auto *typo = primitives->anchorFont();
        typo->setFontWeight(-1);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#de4403"));
        typo->setFontColorDark(QColor("#fae2b9"));
    }
}

void applyLegacy(ColorSchema *colors, PrimitiveSchema *primitives) {
    // primary
    {
        auto *p = colors->palette(ColorVariant::Primary);
        p->setColor(ColorAccent::Shade50, QColor("#c9f6e8"));
        p->setColor(ColorAccent::Shade100, QColor("#a9e8d3"));
        p->setColor(ColorAccent::Shade200, QColor("#80ddbf"));
        p->setColor(ColorAccent::Shade300, QColor("#5ed1aa"));
        p->setColor(ColorAccent::Shade400, QColor("#34c696"));
        p->setColor(ColorAccent::Shade500, QColor("#11ba81"));
        p->setColor(ColorAccent::Shade600, QColor("#00a470"));
        p->setColor(ColorAccent::Shade700, QColor("#168d62"));
        p->setColor(ColorAccent::Shade800, QColor("#007752"));
        p->setColor(ColorAccent::Shade900, QColor("#0d6143"));
        p->setColor(ColorAccent::Shade950, QColor("#004b32"));
        p->setColor(ColorAccent::ContrastDark, QColor("#004b32"));
        p->setColor(ColorAccent::ContrastLight, QColor("#c9f6e8"));
        p->setColor(ColorAccent::Contrast50, QColor("#004b32"));
        p->setColor(ColorAccent::Contrast100, QColor("#004b32"));
        p->setColor(ColorAccent::Contrast200, QColor("#004b32"));
        p->setColor(ColorAccent::Contrast300, QColor("#004b32"));
        p->setColor(ColorAccent::Contrast400, QColor("#004b32"));
        p->setColor(ColorAccent::Contrast500, QColor("#004b32"));
        p->setColor(ColorAccent::Contrast600, QColor("#004b32"));
        p->setColor(ColorAccent::Contrast700, QColor("#c9f6e8"));
        p->setColor(ColorAccent::Contrast800, QColor("#c9f6e8"));
        p->setColor(ColorAccent::Contrast900, QColor("#c9f6e8"));
        p->setColor(ColorAccent::Contrast950, QColor("#c9f6e8"));
    }
    // secondary
    {
        auto *p = colors->palette(ColorVariant::Secondary);
        p->setColor(ColorAccent::Shade50, QColor("#e3e1f7"));
        p->setColor(ColorAccent::Shade100, QColor("#c5c2f4"));
        p->setColor(ColorAccent::Shade200, QColor("#a8a3f0"));
        p->setColor(ColorAccent::Shade300, QColor("#8a84ec"));
        p->setColor(ColorAccent::Shade400, QColor("#6d66e7"));
        p->setColor(ColorAccent::Shade500, QColor("#4f46e5"));
        p->setColor(ColorAccent::Shade600, QColor("#443bc9"));
        p->setColor(ColorAccent::Shade700, QColor("#3933a8"));
        p->setColor(ColorAccent::Shade800, QColor("#2e288d"));
        p->setColor(ColorAccent::Shade900, QColor("#23206e"));
        p->setColor(ColorAccent::Shade950, QColor("#18174f"));
        p->setColor(ColorAccent::ContrastDark, QColor("#18174f"));
        p->setColor(ColorAccent::ContrastLight, QColor("#e3e1f7"));
        p->setColor(ColorAccent::Contrast50, QColor("#18174f"));
        p->setColor(ColorAccent::Contrast100, QColor("#18174f"));
        p->setColor(ColorAccent::Contrast200, QColor("#18174f"));
        p->setColor(ColorAccent::Contrast300, QColor("#18174f"));
        p->setColor(ColorAccent::Contrast400, QColor("#18174f"));
        p->setColor(ColorAccent::Contrast500, QColor("#e3e1f7"));
        p->setColor(ColorAccent::Contrast600, QColor("#e3e1f7"));
        p->setColor(ColorAccent::Contrast700, QColor("#e3e1f7"));
        p->setColor(ColorAccent::Contrast800, QColor("#e3e1f7"));
        p->setColor(ColorAccent::Contrast900, QColor("#e3e1f7"));
        p->setColor(ColorAccent::Contrast950, QColor("#e3e1f7"));
    }
    // tertiary
    {
        auto *p = colors->palette(ColorVariant::Tertiary);
        p->setColor(ColorAccent::Shade50, QColor("#c9eaf8"));
        p->setColor(ColorAccent::Shade100, QColor("#a2dcf7"));
        p->setColor(ColorAccent::Shade200, QColor("#81cef0"));
        p->setColor(ColorAccent::Shade300, QColor("#54c1f1"));
        p->setColor(ColorAccent::Shade400, QColor("#3bb3ea"));
        p->setColor(ColorAccent::Shade500, QColor("#01a5ea"));
        p->setColor(ColorAccent::Shade600, QColor("#1b93cd"));
        p->setColor(ColorAccent::Shade700, QColor("#0e81b5"));
        p->setColor(ColorAccent::Shade800, QColor("#036e9d"));
        p->setColor(ColorAccent::Shade900, QColor("#105c80"));
        p->setColor(ColorAccent::Shade950, QColor("#034a68"));
        p->setColor(ColorAccent::ContrastDark, QColor("#034a68"));
        p->setColor(ColorAccent::ContrastLight, QColor("#c9eaf8"));
        p->setColor(ColorAccent::Contrast50, QColor("#034a68"));
        p->setColor(ColorAccent::Contrast100, QColor("#034a68"));
        p->setColor(ColorAccent::Contrast200, QColor("#034a68"));
        p->setColor(ColorAccent::Contrast300, QColor("#034a68"));
        p->setColor(ColorAccent::Contrast400, QColor("#034a68"));
        p->setColor(ColorAccent::Contrast500, QColor("#034a68"));
        p->setColor(ColorAccent::Contrast600, QColor("#034a68"));
        p->setColor(ColorAccent::Contrast700, QColor("#c9eaf8"));
        p->setColor(ColorAccent::Contrast800, QColor("#c9eaf8"));
        p->setColor(ColorAccent::Contrast900, QColor("#c9eaf8"));
        p->setColor(ColorAccent::Contrast950, QColor("#c9eaf8"));
    }
    // success
    {
        auto *p = colors->palette(ColorVariant::Success);
        p->setColor(ColorAccent::Shade50, QColor("#e9f4d7"));
        p->setColor(ColorAccent::Shade100, QColor("#d5ecb2"));
        p->setColor(ColorAccent::Shade200, QColor("#c1e48b"));
        p->setColor(ColorAccent::Shade300, QColor("#acdc62"));
        p->setColor(ColorAccent::Shade400, QColor("#97d439"));
        p->setColor(ColorAccent::Shade500, QColor("#85cc21"));
        p->setColor(ColorAccent::Shade600, QColor("#74b506"));
        p->setColor(ColorAccent::Shade700, QColor("#669e0b"));
        p->setColor(ColorAccent::Shade800, QColor("#58880d"));
        p->setColor(ColorAccent::Shade900, QColor("#49710b"));
        p->setColor(ColorAccent::Shade950, QColor("#3a5a08"));
        p->setColor(ColorAccent::ContrastDark, QColor("#3a5a08"));
        p->setColor(ColorAccent::ContrastLight, QColor("#e9f4d7"));
        p->setColor(ColorAccent::Contrast50, QColor("#3a5a08"));
        p->setColor(ColorAccent::Contrast100, QColor("#3a5a08"));
        p->setColor(ColorAccent::Contrast200, QColor("#3a5a08"));
        p->setColor(ColorAccent::Contrast300, QColor("#3a5a08"));
        p->setColor(ColorAccent::Contrast400, QColor("#3a5a08"));
        p->setColor(ColorAccent::Contrast500, QColor("#3a5a08"));
        p->setColor(ColorAccent::Contrast600, QColor("#3a5a08"));
        p->setColor(ColorAccent::Contrast700, QColor("#e9f4d7"));
        p->setColor(ColorAccent::Contrast800, QColor("#e9f4d7"));
        p->setColor(ColorAccent::Contrast900, QColor("#e9f4d7"));
        p->setColor(ColorAccent::Contrast950, QColor("#e9f4d7"));
    }
    // warning
    {
        auto *p = colors->palette(ColorVariant::Warning);
        p->setColor(ColorAccent::Shade50, QColor("#f9edc8"));
        p->setColor(ColorAccent::Shade100, QColor("#f5e1a5"));
        p->setColor(ColorAccent::Shade200, QColor("#f4d677"));
        p->setColor(ColorAccent::Shade300, QColor("#f0ca55"));
        p->setColor(ColorAccent::Shade400, QColor("#eebf26"));
        p->setColor(ColorAccent::Shade500, QColor("#eab312"));
        p->setColor(ColorAccent::Shade600, QColor("#d4a207"));
        p->setColor(ColorAccent::Shade700, QColor("#be9100"));
        p->setColor(ColorAccent::Shade800, QColor("#a88100"));
        p->setColor(ColorAccent::Shade900, QColor("#8f7010"));
        p->setColor(ColorAccent::Shade950, QColor("#7a5f06"));
        p->setColor(ColorAccent::ContrastDark, QColor("#7a5f06"));
        p->setColor(ColorAccent::ContrastLight, QColor("#f9edc8"));
        p->setColor(ColorAccent::Contrast50, QColor("#7a5f06"));
        p->setColor(ColorAccent::Contrast100, QColor("#7a5f06"));
        p->setColor(ColorAccent::Contrast200, QColor("#7a5f06"));
        p->setColor(ColorAccent::Contrast300, QColor("#7a5f06"));
        p->setColor(ColorAccent::Contrast400, QColor("#7a5f06"));
        p->setColor(ColorAccent::Contrast500, QColor("#7a5f06"));
        p->setColor(ColorAccent::Contrast600, QColor("#7a5f06"));
        p->setColor(ColorAccent::Contrast700, QColor("#f9edc8"));
        p->setColor(ColorAccent::Contrast800, QColor("#f9edc8"));
        p->setColor(ColorAccent::Contrast900, QColor("#f9edc8"));
        p->setColor(ColorAccent::Contrast950, QColor("#f9edc8"));
    }
    // error
    {
        auto *p = colors->palette(ColorVariant::Error);
        p->setColor(ColorAccent::Shade50, QColor("#fbdbea"));
        p->setColor(ColorAccent::Shade100, QColor("#f2b5d3"));
        p->setColor(ColorAccent::Shade200, QColor("#e88fbc"));
        p->setColor(ColorAccent::Shade300, QColor("#e466a4"));
        p->setColor(ColorAccent::Shade400, QColor("#da418d"));
        p->setColor(ColorAccent::Shade500, QColor("#d31b76"));
        p->setColor(ColorAccent::Shade600, QColor("#bc1a69"));
        p->setColor(ColorAccent::Shade700, QColor("#a80a5c"));
        p->setColor(ColorAccent::Shade800, QColor("#910950"));
        p->setColor(ColorAccent::Shade900, QColor("#7a0743"));
        p->setColor(ColorAccent::Shade950, QColor("#630436"));
        p->setColor(ColorAccent::ContrastDark, QColor("#630436"));
        p->setColor(ColorAccent::ContrastLight, QColor("#fbdbea"));
        p->setColor(ColorAccent::Contrast50, QColor("#630436"));
        p->setColor(ColorAccent::Contrast100, QColor("#630436"));
        p->setColor(ColorAccent::Contrast200, QColor("#630436"));
        p->setColor(ColorAccent::Contrast300, QColor("#630436"));
        p->setColor(ColorAccent::Contrast400, QColor("#fbdbea"));
        p->setColor(ColorAccent::Contrast500, QColor("#fbdbea"));
        p->setColor(ColorAccent::Contrast600, QColor("#fbdbea"));
        p->setColor(ColorAccent::Contrast700, QColor("#fbdbea"));
        p->setColor(ColorAccent::Contrast800, QColor("#fbdbea"));
        p->setColor(ColorAccent::Contrast900, QColor("#fbdbea"));
        p->setColor(ColorAccent::Contrast950, QColor("#fbdbea"));
    }
    // surface
    {
        auto *p = colors->palette(ColorVariant::Surface);
        p->setColor(ColorAccent::Shade50, QColor("#e4e5ec"));
        p->setColor(ColorAccent::Shade100, QColor("#c6c9d7"));
        p->setColor(ColorAccent::Shade200, QColor("#a6adc8"));
        p->setColor(ColorAccent::Shade300, QColor("#8892b3"));
        p->setColor(ColorAccent::Shade400, QColor("#6876a2"));
        p->setColor(ColorAccent::Shade500, QColor("#495a90"));
        p->setColor(ColorAccent::Shade600, QColor("#41507f"));
        p->setColor(ColorAccent::Shade700, QColor("#39466e"));
        p->setColor(ColorAccent::Shade800, QColor("#303b62"));
        p->setColor(ColorAccent::Shade900, QColor("#273152"));
        p->setColor(ColorAccent::Shade950, QColor("#1f2741"));
        p->setColor(ColorAccent::ContrastDark, QColor("#1f2741"));
        p->setColor(ColorAccent::ContrastLight, QColor("#e4e5ec"));
        p->setColor(ColorAccent::Contrast50, QColor("#1f2741"));
        p->setColor(ColorAccent::Contrast100, QColor("#1f2741"));
        p->setColor(ColorAccent::Contrast200, QColor("#1f2741"));
        p->setColor(ColorAccent::Contrast300, QColor("#1f2741"));
        p->setColor(ColorAccent::Contrast400, QColor("#e4e5ec"));
        p->setColor(ColorAccent::Contrast500, QColor("#e4e5ec"));
        p->setColor(ColorAccent::Contrast600, QColor("#e4e5ec"));
        p->setColor(ColorAccent::Contrast700, QColor("#e4e5ec"));
        p->setColor(ColorAccent::Contrast800, QColor("#e4e5ec"));
        p->setColor(ColorAccent::Contrast900, QColor("#e4e5ec"));
        p->setColor(ColorAccent::Contrast950, QColor("#e4e5ec"));
    }

    // Primitives
    primitives->setSpacing(4.0);
    primitives->setTextScaling(1.067);
    primitives->setRadiusBase(6.0);
    primitives->setRadiusContainer(12.0);
    primitives->setBorderWidth(1.0);
    primitives->setDivideWidth(1.0);
    primitives->setRingWidth(1.0);
    primitives->setBodyBackgroundColor(QColor("#ffffff"));
    primitives->setBodyBackgroundColorDark(QColor("#1f2741"));

    // base typography
    {
        auto *typo = primitives->baseFont();
        typo->setFontFamily(QStringLiteral("Inter"));
        typo->setFontWeight(400);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#1f2741"));
        typo->setFontColorDark(QColor("#e4e5ec"));
    }

    // heading typography
    {
        auto *typo = primitives->headingFont();
        typo->setFontWeight(700);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#1f2741"));
        typo->setFontColorDark(QColor("#e4e5ec"));
    }

    // anchor typography
    {
        auto *typo = primitives->anchorFont();
        typo->setFontWeight(-1);
        typo->setItalic(false);
        typo->setLetterSpacing(0.0);
        typo->setFontColor(QColor("#c9f6e8"));
        typo->setFontColorDark(QColor("#c9f6e8"));
    }
}

} // namespace Nandina::Core::Tokens
