//
// Auto-generated by scripts/generate_presets.py
// Do not edit manually.
//

#ifndef NANDINA_THEME_PRESETS_HPP
#define NANDINA_THEME_PRESETS_HPP

#include <QColor>
#include <QString>
#include <QStringList>

#include "color_schema.hpp"
#include "nandina_types.hpp"
#include "primitive_schema.hpp"

namespace Nandina::Core::Tokens {

    /// Apply a built-in theme preset to the given schemas.
    /// Returns false if the preset value is out of range.
    bool applyPreset(Nandina::Types::ThemePreset preset,
                     Nandina::Core::Color::ColorSchema *colors,
                     Nandina::Core::Primitives::PrimitiveSchema *primitives);

    void applyCatppuccin(Nandina::Core::Color::ColorSchema *colors,
                      Nandina::Core::Primitives::PrimitiveSchema *primitives);

    void applyCerberus(Nandina::Core::Color::ColorSchema *colors,
                    Nandina::Core::Primitives::PrimitiveSchema *primitives);

    void applyConcord(Nandina::Core::Color::ColorSchema *colors,
                   Nandina::Core::Primitives::PrimitiveSchema *primitives);

    void applyCrimson(Nandina::Core::Color::ColorSchema *colors,
                   Nandina::Core::Primitives::PrimitiveSchema *primitives);

    void applyFennec(Nandina::Core::Color::ColorSchema *colors,
                  Nandina::Core::Primitives::PrimitiveSchema *primitives);

    void applyLegacy(Nandina::Core::Color::ColorSchema *colors,
                  Nandina::Core::Primitives::PrimitiveSchema *primitives);

} // namespace Nandina::Core::Tokens

#endif // NANDINA_THEME_PRESETS_HPP
